repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-json
      - id: check-added-large-files
      - id: check-toml
      - id: file-contents-sorter
        files: .spellcheck-allowlist.txt
        args: [./yafs/.spellcheck-allowlist.txt]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/srstevenson/nb-clean
    rev: 3.3.0
    hooks:
      - id: nb-clean
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
